version: "2"
services:
  magentophpvarnish:
    image: madhavikh/magentovarnish:v1.0.6
    ports:
      - "8090:80"
    volumes:
      - ./varnish_backup:/var/log/varnish
    links:
      - "magentophpapp"
    depends_on:
      - magentophpapp
         # condition: "service_started"
    environment:
      VARNISH_BACKEND_PORT: 8080
      VARNISH_BACKEND_HOST: magentophpapp
     # TZ: "Asia/Calcutta"
    #command: >
     # sh -c "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && 
     # echo $TZ > /etc/timezone"

  magentophpapp:
    image: madhavikh/magentophp:v1.0.13
    ports:
      - "8080:8080"
    volumes:
      - ./magentosrc:/var/www/html/magento
    links:
      - "solr"
      - "redis"
      - "mysql"
    depends_on:
      - redis
          #condition: service_started
      - solr
          #condition: service_started
      - mysql
         # condition: service_started

   # environment:
    #  TZ: "Asia/Calcutta"
    #command: >
     # sh -c "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && 
     # echo $TZ > /etc/timezone"



  solr:
    image: madhavikh/magentosolr:v3.6.9
    ports:
      - "8983:8983"
   # environment:
    #  TZ: "Asia/Calcutta"
    #command: >
     # sh -c "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && 
     # echo $TZ > /etc/timezone"


  redis:
    image: madhavikh/magentoredis:v_1.0.3
    ports:
      - "6379:6379"
    #environment:
    #  TZ: "Asia/Calcutta"
    #command: >
     # sh -c "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && 
      #echo $TZ > /etc/timezone"


  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./config/mysql/:/var/lib/mysql-files
      - ./mysql_backup:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: root
      #  TZ: "Asia/Calcutta"
    #command: >
     # sh -c "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && 
      #echo $TZ > /etc/timezone"

